# Generated by Django 3.1.3 on 2021-01-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210119_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year_added_to_website',
        ),
    ]
