# Generated by Django 3.1.3 on 2021-01-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210120_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
