# Generated by Django 3.1.3 on 2021-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210120_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cost',
            field=models.TextField(),
        ),
    ]
