# Generated by Django 3.1.3 on 2021-01-21 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_book_go_to_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='go_to_details',
        ),
    ]
