# Generated by Django 3.1.3 on 2021-01-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_book_go_to_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='go_to_details',
            field=models.BooleanField(default=False),
        ),
    ]
