# Generated by Django 3.1.3 on 2021-01-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_book_go_to_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=150),
        ),
    ]
