# Generated by Django 3.1.3 on 2021-01-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210121_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_not_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
